@startuml
actor User

participant "page"
participant "Tag API"
participant auth.ts
participant prisma.ts

User -> "page": Initial request
"page" -> auth.ts: Validate session

alt authenticated
    auth.ts --> "page": Authentication Accepted
else unauthenticated
    auth.ts --> "page": Unauthenticated
    "page" --> User: Redirect to login page
end

"page" --> User: Page render

User -> "Tag API": Create tag (POST)
alt Input valid
    "Tag API" -> prisma.ts: Create tag
    prisma.ts --> "Tag API": Tag saved
    "Tag API" --> User: 201 created
else Input not valid
    "Tag API" --> User: 400 Bad reqeust
end

@enduml
